/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import modelo.datos.Grupo;

/**
 *
 * @author jose_
 */
public final class Grupos extends javax.swing.JDialog {

    Controlador controlador;

    /**
     * Creates new form Grupos
     *
     * @param parent
     * @param modal
     * @param c
     */
    public Grupos(java.awt.Frame parent, boolean modal, Controlador c) {
        super(parent, modal);
        initComponents();
        this.controlador = c;
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/violin.png"));
        setIconImage(icon);
        setTitle("Edicion de Grupos");
        //Centro la pantalla para que esté unida a la pantalla de inicio
        this.setLocation(500 + 152, 250);
        //Actualiza los datos de la tabla
        actualizarTabla();
        ckbx_vigente.addChangeListener((ChangeEvent ce) -> {
            if (ckbx_vigente.isSelected()) {
                spn_fin.setEnabled(false);
            } else {
                spn_fin.setEnabled(true);

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_musicos = new javax.swing.JButton();
        ckbx_vigente = new javax.swing.JCheckBox();
        btn_generos = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        spn_inicio = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        spn_fin = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        btn_esconder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_insert = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_grupo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edicion de Grupos");
        setMaximumSize(new java.awt.Dimension(620, 420));
        setMinimumSize(new java.awt.Dimension(0, 386));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(620, 393));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 386));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_musicos.setText("Gestión Músicos");
        btn_musicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_musicosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_musicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, -1));

        ckbx_vigente.setBackground(new java.awt.Color(255, 255, 255));
        ckbx_vigente.setText("¿Vigente?");
        jPanel2.add(ckbx_vigente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        btn_generos.setText("Gestión Géneros");
        btn_generos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_generos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        txt_id.setBorder(null);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 40));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txt_nombre.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Inicio"));

        spn_inicio.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(spn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(spn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha final"));

        spn_fin.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spn_fin)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(spn_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 230));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 10, 284));

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));

        btn_esconder.setBackground(new java.awt.Color(0, 51, 255));
        btn_esconder.setFont(btn_esconder.getFont().deriveFont(btn_esconder.getFont().getSize()+7f));
        btn_esconder.setForeground(new java.awt.Color(255, 255, 255));
        btn_esconder.setText("◀");
        btn_esconder.setBorder(null);
        btn_esconder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_esconderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(579, Short.MAX_VALUE)
                .addComponent(btn_esconder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(btn_esconder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_insert.setBackground(new java.awt.Color(255, 255, 255));
        btn_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mas.png"))); // NOI18N
        btn_insert.setBorder(null);
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        jPanel4.add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        btn_del.setBackground(new java.awt.Color(255, 255, 255));
        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papelera.png"))); // NOI18N
        btn_del.setBorder(null);
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        jPanel4.add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 60, 60));

        btn_mod.setBackground(new java.awt.Color(255, 255, 255));
        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btn_mod.setBorder(null);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });
        jPanel4.add(btn_mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 60, 60));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("GRUPOS");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        list_grupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        list_grupo.setColumnSelectionAllowed(true);
        list_grupo.getTableHeader().setReorderingAllowed(false);
        list_grupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_grupoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list_grupo);
        list_grupo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (list_grupo.getColumnModel().getColumnCount() > 0) {
            list_grupo.getColumnModel().getColumn(0).setResizable(false);
            list_grupo.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, 210));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 270, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().isEmpty() || txt_nombre.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "No hay datos en el ID o en el nombre",
                    "Faltan datos",
                    JOptionPane.ERROR_MESSAGE);

        } else {

            //comprobar si el checkbox está activo
            if (!ckbx_vigente.isSelected()) {
                Date fechainicial = (Date) spn_inicio.getValue();
                Date fechafin = (Date) spn_fin.getValue();
                //comprobar si la fecha final es mayor que la de nacimiento o creacion
                if (fechainicial.before(fechafin)) {
                    //si es correcto hacer la sql
                    Grupo g = new Grupo();
                    g.setId(Integer.valueOf(txt_id.getText()));
                    g.setNombre(txt_nombre.getText());

                    g.setFormacion(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_inicio.getValue()));

                    g.setDesintegracion(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fin.getValue()));

                    controlador.introducirGrupo(g);
                    new Thread(() -> {
                        new VentanaEmergente(new JFrame(), false, "Creado correctamente").setVisible(true);
                    }).start();
                    //si no, no hacer la sql

                } else {

                    JOptionPane.showMessageDialog(null,
                            "La fecha de inicio es posterior a la del final",
                            "Error en Datos",
                            JOptionPane.ERROR_MESSAGE);
                }
                //si no está seleccionado hacer la sql
            } else {

                Grupo g = new Grupo();
                g.setId(Integer.valueOf(txt_id.getText()));
                g.setNombre(txt_nombre.getText());
                g.setFormacion(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_inicio.getValue()));
                controlador.introducirGrupo(g);
                new Thread(() -> {
                    new VentanaEmergente(new JFrame(), false, "Creado correctamente").setVisible(true);
                }).start();
            }

        }
        actualizarTabla();

    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        //Si el id no está vacío
        if (!txt_id.getText().isEmpty()) {
            int dialogResult = JOptionPane.showConfirmDialog(this,
                    "Va a eliminar este  ¿Está seguro?",
                    "ATENCIÓN",
                    JOptionPane.YES_NO_OPTION);
            //Si selecciono que si en el JOption panel 
            if (dialogResult == JOptionPane.YES_OPTION) {
                controlador.eliminarGrupo(Integer.valueOf(txt_id.getText()));
                actualizarTabla();
                //Vacia los campos
                txt_id.setText("");
                txt_nombre.setText("");

                new Thread(() -> {
                    new VentanaEmergente(new JFrame(), false, "Eliminado correctamente").setVisible(true);
                }).start();
            } else {
                JOptionPane.showMessageDialog(this,
                        "No ha seleccionado nada",
                        "Faltan datos",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        actualizarTabla();

    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        if (txt_id.getText().isEmpty() || txt_nombre.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null,
                    "No hay datos en el id o en el nombre",
                    "Faltan datos",
                    JOptionPane.ERROR_MESSAGE);

        } else {

            //comprobar si el checkbox está activo
            if (!ckbx_vigente.isSelected()) {
                Date fechainicial = (Date) spn_inicio.getValue();
                Date fechafin = (Date) spn_fin.getValue();
                //comprobar si la fecha final es mayor que la de nacimiento o creacion
                if (fechainicial.before(fechafin)) {
                    //si es correcto hacer la sql
                    Grupo g = new Grupo();
                    g.setId(Integer.valueOf(txt_id.getText()));
                    g.setNombre(txt_nombre.getText());

                    g.setFormacion(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_inicio.getValue()));

                    g.setDesintegracion(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fin.getValue()));

                    controlador.modificarGrupo(g);
                    new Thread(() -> {
                        new VentanaEmergente(new JFrame(), false, "Modificado correctamente").setVisible(true);
                    }).start();
                    //si no, no hacer la sql
                } else {

                    JOptionPane.showMessageDialog(null,
                            "La fecha de inicio es mayor que la de fin",
                            "Fechas erroneas",
                            JOptionPane.ERROR_MESSAGE);
                }
                //si no está seleccionado hacer la sql
            } else {

                Grupo g = new Grupo();
                g.setId(Integer.valueOf(txt_id.getText()));
                g.setNombre(txt_nombre.getText());
                g.setFormacion(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_inicio.getValue()));
                controlador.modificarGrupo(g);
                new Thread(() -> {
                    new VentanaEmergente(new JFrame(), false, "Modificado correctamente").setVisible(true);
                }).start();
            }

        }
        actualizarTabla();

    }//GEN-LAST:event_btn_modActionPerformed

    private void list_grupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_grupoMouseClicked
        //Cuando clicas un grupo pone los datos en la parte izquierda
        Grupo g = controlador.sacarGrupo(Integer.valueOf(String.valueOf(list_grupo.getModel().getValueAt(list_grupo.getSelectedRow(), 0))));
        //Se establecen los datos en los campos concretos
        txt_id.setText(String.valueOf(g.getId()));
        txt_nombre.setText(g.getNombre());
        //Se le da formato a la fecha para ponerla en el spinner
        String fecha = g.getFormacion();
        String[] fechaseparada = fecha.split("-");
        //Se mete en un calendario para poder introducirla en el spinner
        Calendar calendar = new GregorianCalendar(Integer.valueOf(fechaseparada[0]), Integer.valueOf(fechaseparada[1]), Integer.valueOf(fechaseparada[2]));
        spn_inicio.setValue(calendar.getTime());
        //Si el campo desintagracion no es nulo introduce los datos en el spinner
        if (g.getDesintegracion() != null) {
            ckbx_vigente.setSelected(true);
            fecha = g.getDesintegracion();
            fechaseparada = fecha.split("-");
            Calendar calendar1 = new GregorianCalendar(Integer.valueOf(fechaseparada[0]), Integer.valueOf(fechaseparada[1]), Integer.valueOf(fechaseparada[2]));
            spn_fin.setValue(calendar1.getTime());
        } else {
            ckbx_vigente.setSelected(false);
        }

    }//GEN-LAST:event_list_grupoMouseClicked

    //Si quieres insertar la relación con generos
    private void btn_generosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generosActionPerformed

        if (txt_id.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null,
                    "Selecciona un grupo antes de esta opción",
                    "Selecciona un Grupo",
                    JOptionPane.ERROR_MESSAGE);

        } else {
            GrupoGenero gg = new GrupoGenero(new JFrame(), true, controlador, Integer.valueOf(txt_id.getText()));
            gg.setVisible(true);
        }

    }//GEN-LAST:event_btn_generosActionPerformed

    //Si quieres insertar la relación con musicos
    private void btn_musicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_musicosActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null,
                    "Selecciona un grupo antes de esta opción",
                    "Selecciona un Grupo",
                    JOptionPane.ERROR_MESSAGE);

        } else {
            GrupoMusico gm = new GrupoMusico(new JFrame(), true, controlador);
            gm.insentarMusicos(Integer.valueOf(txt_id.getText()));
            gm.setVisible(true);

        }

    }//GEN-LAST:event_btn_musicosActionPerformed

    private void btn_esconderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_esconderActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_esconderActionPerformed

    //Actualiza la tabla borrando antes lo que hubiese dentro
    public void actualizarTabla() {

        ArrayList<Grupo> grupos = controlador.sacarGrupos();
        DefaultTableModel modelo = (DefaultTableModel) list_grupo.getModel();
        for (int i = 0; i < list_grupo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        for (int i = 0; i < grupos.size(); i++) {
            //Sacp los datos del grupo para ponerlo en la tabla
            String[] g1 = {String.valueOf(grupos.get(i).getId()), grupos.get(i).getNombre()};

            modelo.addRow(g1);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_esconder;
    private javax.swing.JButton btn_generos;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_mod;
    private javax.swing.JButton btn_musicos;
    private javax.swing.JCheckBox ckbx_vigente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable list_grupo;
    private javax.swing.JSpinner spn_fin;
    private javax.swing.JSpinner spn_inicio;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
