/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import modelo.datos.Grupo;
import modelo.datos.Musico;

/**
 *
 * @author jose_
 */
public class GrupoMusico extends javax.swing.JDialog {

    Controlador controlador;

    //booleano que me dice si hay musicos o grupos en la tabla
    //si es insertaMusicos es true, si no hay musicos es false
    boolean insertaMusicos = false;

    //id del grupo
    int idgrupo;

    //id del insertaMusicos
    int idmusico;
    //columna seleccionada de la lista de la izquierda(listaDatos) 
    int seleccionado;
    //columna seleccionada de la lista de la dereca(listaRelacion) 
    int seleccionado2;

    /**
     * Creates new form GrupoMusico
     *
     * @param parent
     * @param modal
     * @param c
     */
    public GrupoMusico(java.awt.Frame parent, boolean modal, Controlador c) {
        super(parent, modal);
        initComponents();
        this.controlador = c;
        //centrar pantalla
        this.setLocationRelativeTo(this);
        //Poner el icono
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/violin.png"));
        setIconImage(icon);
        setTitle("Edicion de Relación Grupo Musicos");
        //ChangeListener de check box
        ckbx_grupo.addChangeListener((ChangeEvent ce) -> {
            if (ckbx_grupo.isSelected()) {
                spn_fin.setEnabled(false);
            } else {
                spn_fin.setEnabled(true);

            }
        });
        ckbx_grupo.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ckbx_grupo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        spn_inicio = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        spn_fin = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        txt_intrumento = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDatos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaRelacion = new javax.swing.JTable();
        relacion = new javax.swing.JLabel();
        listado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incluir");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ckbx_grupo.setBackground(new java.awt.Color(255, 255, 255));
        ckbx_grupo.setText("¿Está en el grupo?");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha Inicio"));

        spn_inicio.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(spn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(spn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha fin"));

        spn_fin.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spn_fin, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(spn_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrumento"));

        txt_intrumento.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txt_intrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txt_intrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mas.png"))); // NOI18N
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papelera.png"))); // NOI18N
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        listaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaDatos.setColumnSelectionAllowed(true);
        listaDatos.getTableHeader().setReorderingAllowed(false);
        listaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaDatos);
        listaDatos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        listaRelacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaRelacion.setColumnSelectionAllowed(true);
        listaRelacion.getTableHeader().setReorderingAllowed(false);
        listaRelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaRelacionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listaRelacion);
        listaRelacion.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        relacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        relacion.setText("Relacion GRUPO-MUSICO");

        listado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        listado.setText("Datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ckbx_grupo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(listado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(relacion)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relacion)
                    .addComponent(listado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckbx_grupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_mod)
                                .addComponent(btn_insert)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed

        if (!txt_intrumento.getText().isEmpty()) {

            String fecha_final = null;
            String fecha_inicio = new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_inicio.getValue());
            if (ckbx_grupo.isSelected()) {
            } else {
                fecha_final = new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fin.getValue());
            }
            //Si he insertado musicos en la tabla...
            if (insertaMusicos) {

                controlador.introducirGrupoMusico(idgrupo, Integer.valueOf(String.valueOf(listaDatos.getModel().getValueAt(seleccionado, 0))), txt_intrumento.getText(), fecha_inicio, fecha_final);

            } else {
                controlador.introducirGrupoMusico(Integer.valueOf((String) listaDatos.getModel().getValueAt(seleccionado, 0)), idmusico, txt_intrumento.getText(), fecha_inicio, fecha_final);

            }
            insertarRelacionMusicoGrupo();
            new Thread(() -> {
                new VentanaEmergente(new JFrame(), false, "Creado correctamente").setVisible(true);
            }).start();
        } else {
            JOptionPane.showMessageDialog(null,
                    "NO HAY DATOS EN EL INSTRUMENTO",
                    "FALTAN DATOS",
                    JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        //Si he insertado musicos en la tabla...
        if (insertaMusicos) {

            controlador.EliminaGrupoMusico(idgrupo, Integer.valueOf(String.valueOf(listaRelacion.getModel().getValueAt(seleccionado2, 0))));

        } else {
            controlador.EliminaGrupoMusico(Integer.valueOf((String) listaRelacion.getModel().getValueAt(seleccionado2, 0)), idmusico);

        }
        txt_intrumento.setText("");
        insertarRelacionMusicoGrupo();
        new Thread(() -> {
            new VentanaEmergente(new JFrame(), false, "Eliminado correctamente").setVisible(true);
        }).start();
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        // TODO add your handling code here:
        String fecha_inicio = new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_inicio.getValue());
        String fecha_final = new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fin.getValue());
//Si he insertado musicos en la tabla...
        if (insertaMusicos) {

            controlador.ActualizaGrupoMusico(idgrupo, Integer.valueOf(String.valueOf(listaRelacion.getModel().getValueAt(seleccionado2, 0))), txt_intrumento.getText(), fecha_inicio, fecha_final);

        } else {
            controlador.ActualizaGrupoMusico(Integer.valueOf((String) listaRelacion.getModel().getValueAt(seleccionado2, 0)), idmusico, txt_intrumento.getText(), fecha_inicio, fecha_final);

        }
        insertarRelacionMusicoGrupo();
        new Thread(() -> {
            new VentanaEmergente(new JFrame(), false, "Modificado correctamente").setVisible(true);
        }).start();

    }//GEN-LAST:event_btn_modActionPerformed

    private void listaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDatosMouseClicked
        // TODO add your handling code here:
        seleccionado = listaDatos.getSelectedRow();

    }//GEN-LAST:event_listaDatosMouseClicked

    private void listaRelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaRelacionMouseClicked
        // TODO add your handling code here:
        //Selecciona de la tabla de las relaciones
        seleccionado2 = listaRelacion.getSelectedRow();
        ArrayList<String> respuesta = null;
        //Si he insertado musicos en la tabla...

        if (insertaMusicos) {
            System.out.println(Integer.valueOf((String) listaRelacion.getModel().getValueAt(seleccionado2, 0)));
            respuesta = controlador.sacarMusicoGrupo(idgrupo, Integer.valueOf((String) listaRelacion.getModel().getValueAt(seleccionado2, 0)));

        } else {
            respuesta = controlador.sacarMusicoGrupo(Integer.valueOf((String) listaRelacion.getModel().getValueAt(seleccionado2, 0)), idmusico);

        }
        //Inserta los datos que ha recogido al clicar en una fila de la tabla de relaciones
        //Respuesta tiene 3 campos, instrumento, fecha inicio, fecha final
        txt_intrumento.setText(respuesta.get(0));
        String fecha = respuesta.get(1);
        //Spliteo la fecha para poder interoducirla al Gregoria Calendar
        String[] fechaseparada = fecha.split("-");
        Calendar calendar = new GregorianCalendar(Integer.valueOf(fechaseparada[0]), Integer.valueOf(fechaseparada[1]), Integer.valueOf(fechaseparada[2]));
        spn_inicio.setValue(calendar.getTime());
        System.out.println(respuesta.get(2));
        //Si no me devuelve ninguna fecha
        if (respuesta.get(2) != null) {
            fecha = respuesta.get(2);
            ckbx_grupo.setSelected(false);

            fechaseparada = fecha.split("-");
            calendar = new GregorianCalendar(Integer.valueOf(fechaseparada[0]), Integer.valueOf(fechaseparada[1]), Integer.valueOf(fechaseparada[2]));
            spn_fin.setValue(calendar.getTime());

        } else {
            ckbx_grupo.setSelected(true);

        }

    }//GEN-LAST:event_listaRelacionMouseClicked

    //Este metodo será usado cuando lo llame un Grupo
    public void insentarMusicos(int idgrupo) {

        //Inserto Musicos a la tabla
        listado.setText("Listado de Músicos");
        setTitle("Gestión con Músicos");
        relacion.setText("Músicos en el grupo: " + controlador.sacarGrupo(idgrupo).getNombre());
        this.idgrupo = idgrupo;
        insertaMusicos = true;
        ArrayList<Musico> musicos = controlador.sacarMusicos();

        DefaultTableModel modelo = (DefaultTableModel) listaDatos.getModel();
        for (int i = 0; i < listaDatos.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        for (int i = 0; i < musicos.size(); i++) {
            String[] g1 = {String.valueOf(musicos.get(i).getId()), musicos.get(i).getNombre()};
            modelo.addRow(g1);

        }
        insertarRelacionMusicoGrupo();
    }

    //Este metodo será usado cuando lo llame un Musico
    public void insertarGrupos(int idmusico) {
        //Inserto grupos a la tabla
        listado.setText("Listado de Grupos");
        setTitle("Gestión con Grupos");

        relacion.setText("Grupos del músico: " + controlador.sacarMusico(idmusico).getNombre());
        txt_intrumento.setText(controlador.sacarMusico(idmusico).getInstrumento());
        this.idmusico = idmusico;
        insertaMusicos = false;
        ArrayList<Grupo> grupos = controlador.sacarGrupos();

        DefaultTableModel modelo = (DefaultTableModel) listaDatos.getModel();
        for (int i = 0; i < grupos.size(); i++) {
            String[] g1 = {String.valueOf(grupos.get(i).getId()), grupos.get(i).getNombre()};
            modelo.addRow(g1);
            listaDatos.setModel(modelo);

        }
        insertarRelacionMusicoGrupo();

    }

    //Insertar la relacion entre el Musico y el Grupo
    public void insertarRelacionMusicoGrupo() {
//Si lo ha llamado un inserta musicos

        if (!insertaMusicos) {

            ArrayList<Grupo> grupos = controlador.sacarGrupoporMusico(idmusico);
            DefaultTableModel modelo = (DefaultTableModel) listaRelacion.getModel();
            for (int i = 0; i < listaRelacion.getRowCount(); i++) {
                modelo.removeRow(i);
                i -= 1;
            }
            for (int i = 0; i < grupos.size(); i++) {
                String[] g1 = {String.valueOf(grupos.get(i).getId()), grupos.get(i).getNombre()};
                modelo.addRow(g1);
                listaRelacion.setModel(modelo);

            }
//Si lo ha llamado un inserta grupos 
        } else {
            ArrayList<Musico> musicos = controlador.sacarMusicoporGrupo(idgrupo);
            DefaultTableModel modelo = (DefaultTableModel) listaRelacion.getModel();
            for (int i = 0; i < listaRelacion.getRowCount(); i++) {
                modelo.removeRow(i);
                i -= 1;
            }
            for (int i = 0; i < musicos.size(); i++) {
                String[] g1 = {String.valueOf(musicos.get(i).getId()), musicos.get(i).getNombre()};
                modelo.addRow(g1);
                listaRelacion.setModel(modelo);
            }

        }
    }
    //Cuando seleccione un grupo al que relacionar el insertaMusicos que estoy creando
    //deberé introducir las fechas y toda la pesca
    //posteriormente cuando le de a añadir me aparecerá en la ventana izquierda

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_mod;
    private javax.swing.JCheckBox ckbx_grupo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listaDatos;
    private javax.swing.JTable listaRelacion;
    private javax.swing.JLabel listado;
    private javax.swing.JLabel relacion;
    private javax.swing.JSpinner spn_fin;
    private javax.swing.JSpinner spn_inicio;
    private javax.swing.JTextField txt_intrumento;
    // End of variables declaration//GEN-END:variables
}
