/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import modelo.datos.Genero;

/**
 *
 * @author jose_
 */
public final class GrupoGenero extends javax.swing.JDialog {

    Controlador controlador;
    int idgrupo;

    /**
     * Creates new form GrupoGenero
     *
     * @param parent
     * @param modal
     * @param c
     * @param idgrupo
     */
    public GrupoGenero(java.awt.Frame parent, boolean modal, Controlador c, int idgrupo) {

        super(parent, modal);
        this.setLocationRelativeTo(this);
        this.idgrupo = idgrupo;
        this.setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/violin.png"));
        setIconImage(icon);
        setTitle("Gestión de Géneros");
        this.controlador = c;
        initComponents();
        actualizartabla();
        meterGeneros();
        relacion.setText("Géneros que tiene: "+ controlador.sacarGrupo(idgrupo).getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_insert = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_generos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        listarelacion = new javax.swing.JTable();
        relacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mas.png"))); // NOI18N
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papelera.png"))); // NOI18N
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        lista_generos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lista_generos.setColumnSelectionAllowed(true);
        lista_generos.getTableHeader().setReorderingAllowed(false);
        lista_generos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lista_generosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lista_generos);
        lista_generos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        listarelacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listarelacion.setColumnSelectionAllowed(true);
        listarelacion.getTableHeader().setReorderingAllowed(false);
        listarelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarelacionMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listarelacion);
        listarelacion.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        relacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        relacion.setText("Géneros que tiene este grupo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Lista de Géneros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(relacion)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_insert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relacion)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_insert))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed

        controlador.relacionGrupoGenero(Integer.valueOf(String.valueOf(lista_generos.getModel().getValueAt(lista_generos.getSelectedRow(), 0))), idgrupo);
        new Thread(() -> {
            new VentanaEmergente(new JFrame(), false, "Creado correctamente").setVisible(true);
        }).start();
        actualizartabla();

    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:

        controlador.eliminaGrupoGenero(Integer.valueOf(String.valueOf(listarelacion.getModel().getValueAt(listarelacion.getSelectedRow(), 0))), idgrupo);
        actualizartabla();
        new Thread(() -> {
            new VentanaEmergente(new JFrame(), false, "Eliminado correctamente").setVisible(true);
        }).start();

    }//GEN-LAST:event_btn_delActionPerformed

    private void lista_generosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lista_generosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lista_generosMouseClicked

    private void listarelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarelacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listarelacionMouseClicked

    public void actualizartabla() {

        ArrayList<Genero> generos = controlador.sacarGrupoGeneros(idgrupo);
        DefaultTableModel modelo = (DefaultTableModel) listarelacion.getModel();
        for (int i = 0; i < listarelacion.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        for (int i = 0; i < generos.size(); i++) {
            String[] g1 = {String.valueOf(generos.get(i).getId()), generos.get(i).getDescripcion()};
            modelo.addRow(g1);
            listarelacion.setModel(modelo);

        }

    }

    public void meterGeneros() {

        ArrayList<Genero> generos = controlador.sacarGeneros();

        DefaultTableModel modelo = (DefaultTableModel) lista_generos.getModel();
        for (int i = 0; i < lista_generos.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }

        for (int i = 0; i < generos.size(); i++) {
            String[] g1 = {String.valueOf(generos.get(i).getId()), generos.get(i).getDescripcion()};

            modelo.addRow(g1);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_insert;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable lista_generos;
    private javax.swing.JTable listarelacion;
    private javax.swing.JLabel relacion;
    // End of variables declaration//GEN-END:variables
}
