/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import modelo.datos.Musico;

/**
 *
 * @author jose_
 */
public class Musicos extends javax.swing.JDialog {

    Controlador controlador;

    /**
     * Creates new form Musicos
     *
     * @param parent
     * @param modal
     * @param c
     */
    public Musicos(java.awt.Frame parent, boolean modal, Controlador c) {
        super(parent, modal);
        this.setLocation(500 + 153, 250);
        initComponents();
        this.controlador = c;
        this.setAlwaysOnTop(false);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/violin.png"));
        setIconImage(icon);
        setTitle("Edicion de Musicos");
        actualizarTabla();
        ckbx_muerto.addChangeListener((ChangeEvent ce) -> {
            if (ckbx_muerto.isSelected()) {
                spn_fechaMuerte.setEnabled(false);
            } else {
                spn_fechaMuerte.setEnabled(true);

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btn_grupo = new javax.swing.JButton();
        ckbx_muerto = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txt_nombre = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txt_instrumento = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txt_lugarNacimiento = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        spn_fechaNacimiento = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        spn_fechaMuerte = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        btn_insert = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        btn_mod = new javax.swing.JButton();
        label_titulo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_esconder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_musicos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edicion de músicos");
        setMaximumSize(new java.awt.Dimension(640, 2147483647));
        setMinimumSize(new java.awt.Dimension(640, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMaximumSize(new java.awt.Dimension(640, 640));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 420));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, 280));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_grupo.setText("Añadir a Grupo");
        btn_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grupoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, -1));

        ckbx_muerto.setBackground(new java.awt.Color(255, 255, 255));
        ckbx_muerto.setText("¿Vivo?");
        jPanel2.add(ckbx_muerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        txt_id.setBorder(null);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txt_nombre.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Instrumento"));

        txt_instrumento.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_instrumento, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(txt_instrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugar de Nacimiento"));

        txt_lugarNacimiento.setBorder(null);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_lugarNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(txt_lugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de nacimiento"));

        spn_fechaNacimiento.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spn_fechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(spn_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de muerte"));

        spn_fechaMuerte.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spn_fechaMuerte, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(spn_fechaMuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 250));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btn_insert.setBackground(new java.awt.Color(255, 255, 255));
        btn_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mas.png"))); // NOI18N
        btn_insert.setBorder(null);
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_del.setBackground(new java.awt.Color(255, 255, 255));
        btn_del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papelera.png"))); // NOI18N
        btn_del.setBorder(null);
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        btn_mod.setBackground(new java.awt.Color(255, 255, 255));
        btn_mod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        btn_mod.setBorder(null);
        btn_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btn_insert)
                .addGap(51, 51, 51)
                .addComponent(btn_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_mod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_del, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_insert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 325, 270, -1));

        label_titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_titulo.setText("Músicos");
        jPanel1.add(label_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 90, 20));

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));

        btn_esconder.setBackground(new java.awt.Color(0, 51, 255));
        btn_esconder.setFont(btn_esconder.getFont().deriveFont(btn_esconder.getFont().getSize()+7f));
        btn_esconder.setForeground(new java.awt.Color(255, 255, 255));
        btn_esconder.setText("◀");
        btn_esconder.setBorder(null);
        btn_esconder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_esconderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(599, Short.MAX_VALUE)
                .addComponent(btn_esconder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(btn_esconder, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        list_musicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        list_musicos.setColumnSelectionAllowed(true);
        list_musicos.getTableHeader().setReorderingAllowed(false);
        list_musicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_musicosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list_musicos);
        list_musicos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 270, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:

        if (txt_id.getText().isEmpty() || txt_nombre.getText().isEmpty() || txt_instrumento.getText().isEmpty() || txt_lugarNacimiento.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null,
                     "No hay datos en el id, nombre o instrumento",
                    "Faltan datos",
                    JOptionPane.ERROR_MESSAGE);

        } else {

            //comprobar si el checkbox está activo
            if (!ckbx_muerto.isSelected()) {
                Date fechainicial = (Date) spn_fechaNacimiento.getValue();
                Date fechafin = (Date) spn_fechaMuerte.getValue();
                //comprobar si la fecha final es mayor que la de nacimiento o creacion
                if (fechainicial.before(fechafin)) {
                    //si es correcto hacer la sql
                    Musico m = new Musico();
                    m.setId(Integer.valueOf(txt_id.getText()));
                    m.setNombre(txt_nombre.getText());
                    m.setInstrumento(txt_instrumento.getText());
                    m.setLugarnacimiento(txt_lugarNacimiento.getText());
                    m.setFecha_nacimiento(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fechaNacimiento.getValue()));
                    m.setFecha_muerte(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fechaMuerte.getValue()));
                    controlador.introducirMusico(m);
                    new Thread(() -> {
                        new VentanaEmergente(new JFrame(), false, "Creado correctamente").setVisible(true);
                    }).start();
                    //si no, no hacer la sql
                } else {

                    JOptionPane.showMessageDialog(null,
                             "La fecha de nacimiento es mayor que la de muerte",
                            "Error en las fechas",
                            JOptionPane.ERROR_MESSAGE);
                }
                //si no está seleccionado hacer la sql
            } else {
                new Thread(() -> {
                    new VentanaEmergente(new JFrame(), false, "Creado correctamente").setVisible(true);
                }).start();
                Musico m = new Musico();
                m.setId(Integer.valueOf(txt_id.getText()));
                m.setNombre(txt_nombre.getText());
                m.setInstrumento(txt_instrumento.getText());
                m.setLugarnacimiento(txt_lugarNacimiento.getText());
                m.setFecha_nacimiento(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fechaNacimiento.getValue()));
                controlador.introducirMusico(m);
            }

        }
        actualizarTabla();

    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modActionPerformed
        // TODO add your handling code here:

        if (txt_id.getText().isEmpty() || txt_nombre.getText().isEmpty() || txt_instrumento.getText().isEmpty() || txt_lugarNacimiento.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null,
                    "No hay datos en el id, nombre o instrumento",
                    "Faltan datos",
                    JOptionPane.ERROR_MESSAGE);

        } else {

            //comprobar si el checkbox está activo
            if (!ckbx_muerto.isSelected()) {
                Date fechainicial = (Date) spn_fechaNacimiento.getValue();
                Date fechafin = (Date) spn_fechaMuerte.getValue();
                //comprobar si la fecha final es mayor que la de nacimiento o creacion
                if (fechainicial.before(fechafin)) {
                    //si es correcto hacer la sql
                    Musico m = new Musico();
                    m.setId(Integer.valueOf(txt_id.getText()));
                    m.setNombre(txt_nombre.getText());
                    m.setInstrumento(txt_instrumento.getText());
                    m.setLugarnacimiento(txt_lugarNacimiento.getText());
                    m.setFecha_nacimiento(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fechaNacimiento.getValue()));
                    m.setFecha_muerte(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fechaMuerte.getValue()));
                    controlador.modificarMusico(m);
                    new Thread(() -> {
                        new VentanaEmergente(new JFrame(), false, "Modificado correctamente").setVisible(true);
                    }).start();
                    //si no, no hacer la sql
                } else {

                    JOptionPane.showMessageDialog(null,
                            "La fecha de nacimiento es mayor que la de muerte",
                            "Error en las fechas",
                            JOptionPane.ERROR_MESSAGE);
                }
                //si no está seleccionado hacer la sql
            } else {
                Musico m = new Musico();
                m.setId(Integer.valueOf(txt_id.getText()));
                m.setNombre(txt_nombre.getText());
                m.setInstrumento(txt_instrumento.getText());
                m.setLugarnacimiento(txt_lugarNacimiento.getText());
                m.setFecha_nacimiento(new SimpleDateFormat("yyyy-MM-dd").format((Date) spn_fechaNacimiento.getValue()));
                m.setFecha_muerte(null);
                controlador.modificarMusico(m);
                new Thread(() -> {
                    new VentanaEmergente(new JFrame(), false, "Modificado correctamente").setVisible(true);
                }).start();
            }

        }
        actualizarTabla();

    }//GEN-LAST:event_btn_modActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
        if (!txt_id.getText().isEmpty()) {
            int dialogResult = JOptionPane.showConfirmDialog(null,
                    "Va a eliminar este  ¿Está seguro?",
                    "ATENCIÓN",
                    JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                controlador.eliminarMusico(Integer.valueOf(txt_id.getText()));
                actualizarTabla();
                new Thread(() -> {
                    new VentanaEmergente(new JFrame(), false, "Eliminado correctamente").setVisible(true);
                }).start();
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "No ha seleccionado nada",
                    "Seleccione algo",
                    JOptionPane.ERROR_MESSAGE);
        }
        actualizarTabla();

    }//GEN-LAST:event_btn_delActionPerformed

    private void list_musicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_musicosMouseClicked
        // TODO add your handling code here:

        Musico m = controlador.sacarMusico(Integer.valueOf(String.valueOf(list_musicos.getModel().getValueAt(list_musicos.getSelectedRow(), 0))));
        txt_id.setText(String.valueOf(m.getId()));
        txt_instrumento.setText(m.getInstrumento());
        txt_lugarNacimiento.setText(m.getLugarnacimiento());
        txt_nombre.setText(m.getNombre());
        String fecha = m.getFecha_nacimiento();
        String[] fechaseparada = fecha.split("-");
        Calendar calendar = new GregorianCalendar(Integer.valueOf(fechaseparada[0]), Integer.valueOf(fechaseparada[1]), Integer.valueOf(fechaseparada[2]));
        spn_fechaNacimiento.setValue(calendar.getTime());
        if (m.getFecha_muerte() != null) {
            ckbx_muerto.setSelected(true);
            fecha = m.getFecha_muerte();
            fechaseparada = fecha.split("-");
            calendar = new GregorianCalendar(Integer.valueOf(fechaseparada[0]), Integer.valueOf(fechaseparada[1]), Integer.valueOf(fechaseparada[2]));
            spn_fechaMuerte.setValue(calendar.getTime());
        } else {
            ckbx_muerto.setSelected(false);
        }

    }//GEN-LAST:event_list_musicosMouseClicked

    private void btn_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grupoActionPerformed
        // TODO add your handling code here:

        GrupoMusico gm = new GrupoMusico(new JFrame(), true, controlador);
        gm.insertarGrupos(Integer.valueOf(txt_id.getText()));
        gm.setVisible(true);

    }//GEN-LAST:event_btn_grupoActionPerformed

    private void btn_esconderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_esconderActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_esconderActionPerformed
    public void actualizarTabla() {
        try {
            ArrayList<Musico> musicos = controlador.sacarMusicos();

            DefaultTableModel modelo = (DefaultTableModel) list_musicos.getModel();
            for (int i = 0; i < list_musicos.getRowCount(); i++) {
                modelo.removeRow(i);
                i -= 1;
            }
            for (int i = 0; i < musicos.size(); i++) {
                String[] g1 = {String.valueOf(musicos.get(i).getId()), musicos.get(i).getNombre()};
                modelo.addRow(g1);
            }
        } catch (Exception e) {
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_esconder;
    private javax.swing.JButton btn_grupo;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_mod;
    private javax.swing.JCheckBox ckbx_muerto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JTable list_musicos;
    private javax.swing.JSpinner spn_fechaMuerte;
    private javax.swing.JSpinner spn_fechaNacimiento;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_instrumento;
    private javax.swing.JTextField txt_lugarNacimiento;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
